version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    assignees:
      - redeboer
      - Zeyna777
    commit-message:
      prefix: MAINT
    labels:
      - 🔨 Maintenance
    schedule:
      interval: monthly
