[dependencies]
julia = {version = "*", channel = "https://repo.prefix.dev/julia-forge"}

[tasks.doc]
cmd = "quarto render docs"

[tasks.doclive]
cmd = "quarto preview docs --port 7000"

[workspace]
authors = ["Lena Pöpping <80910285+Zeyna777@users.noreply.github.com>"]
channels = ["https://repo.prefix.dev/julia-forge"]
name = "k-matrix-day-2024"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"
