bibliography: references.bib
csl: apa.csl
execute:
  cache: true
format:
  html:
    css: styles.css
    theme:
      light: flatly
      dark: darkly
    toc: true
number-depth: 3
project:
  output-dir: _build/html
  render:
    - experimental-data.csv
    - index.qmd
    - finding-poles.ipynb
    - finding-poles-2channels.ipynb
    - k-matrix.html
    - resources.qmd
  resources:
    - lite/
    - references.bib
  type: website
website:
  description: Website for the International K-Matrix Day 2025
  draft-mode: visible
  favicon: favicon.ico
  navbar:
    background: "#17365c"
    foreground: "#e7e7e7"
    logo: images/rub-white.svg
    logo-href: https://rub.de
    title: false
  page-navigation: true
  repo-actions:
    - edit
    - issue
    - source
  repo-subdir: docs
  repo-url: https://github.com/RUB-EP1/kmatrix-day-2025
  sidebar:
    contents:
      - file: index.qmd
        icon: house
        text: Home
      - text: Live coding session
        icon: play
        contents:
          - href: k-matrix.html
            icon: 1-circle
            text: Construction of $K$ matrices
          - file: finding-poles.ipynb
            icon: 2-circle
      - text: Bonus material
        icon: journal-code
        contents:
          - file: finding-poles-2channels.ipynb
      - text: Resources
        icon: book
        file: resources.qmd
      - text: ---
      - text: K-Matrix Day 2024
        href: https://rub-ep1.github.io/kmatrix-day-2024
        icon: box-arrow-up-right
    search: true
    tools:
      - href: https://github.com/RUB-EP1/kmatrix-day-2025
        icon: github
        text: GitHub Repository
      - href: https://amplitude-analysis.slack.com/archives/C08MJ655W6R
        icon: slack
        text: Slack Channel
      - href: https://indico.global/event/14144
        icon: calendar-event
        text: Indico Event
      - href: lite/lab/index.html
        icon: code-square
        text: Live coding with Jupyter Lite
