format:
  html:
    anchor-sections: false
    theme:
      dark: darkly
      light: flatly
    css: styles.css
number-depth: 3
project:
  output-dir: _build/html
  type: website
website:
  description: Website for the International K-Matrix Day 2025
  favicon: favicon.ico
  navbar:
    background: "#17365c"
    foreground: "#e7e7e7"
    logo: images/rub-white.svg
    logo-href: https://rub.de
    pinned: true
    title: false
    website:
  sidebar:
    contents:
      - file: index.qmd
        icon: house
        text: Home
      - text: Notebooks
        icon: journal-code
        contents:
          - file: finding-poles.ipynb
      - text: Useful links
        icon: book
      - text: ---
      - text: K-Matrix Day 2024
        href: https://rub-ep1.github.io/kmatrix-day-2024
        icon: box-arrow-up-right
    search: true
    style: docked
    tools:
      - href: https://github.com/RUB-EP1/kmatrix-day-2025
        icon: github
      - href: https://amplitude-analysis.slack.com/archives/C08KUF36Y6S
        icon: slack
